Travis: Stop using ASAN for swtpm since one test case fails
It's not possible to recreate the issue with the failing test case
locally on Xenial, so just disable the ASAN usage on swtpm by disabling
the CFLAGS variable.

The one failing test case show this. All other ones work.

FAIL: test_parameters

=====================

Test 0: SUCCESS with parameters ''.
Test 1: SUCCESS with parameters '--createek'.
Test 2: ==27310==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
ERROR: Test with parameters '--take-ownership' failed.
FAIL test_parameters (exit status: 1)

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>