swtpm/swtpm_setup: Initialize variables with NULL for RPM build
When building an rpm with swtpm.spec on Fedora 40 this type of errors
appear on variables that normally do not need to be initialized.

In file included from /usr/include/glib-2.0/glib.h:117,
                 from profile.c:14:
In function ‘g_autoptr_cleanup_generic_gfree’,
    inlined from ‘profile_gather_local’ at profile.c:307:23,
    inlined from ‘profile_printall’ at profile.c:366:10:
/usr/include/glib-2.0/glib/glib-autocleanups.h:32:3: error: ‘dir’ may be used uninitialized [-Werror=maybe-uninitialized]
   32 |   g_free (*pp);
      |   ^~~~~~~~~~~~
profile.c: In function ‘profile_printall’:
profile.c:307:23: note: ‘dir’ was declared here
  307 |     g_autofree gchar *dir;
      |                       ^~~

Include string.h since in some older build environments strcmp and strlen
do not have prototypes otherwise.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>