swtpm_cert: Cast parameter passed to isspace to int (Cygwin)
Cygwin requires an explicit cast of the char parameter passed to isspace
to int to fix this issue:

ek-cert.c: In function ‘main’:
ek-cert.c:1605:28: error: array subscript has type ‘char’ [-Werror=char-subscripts]
 1605 |             while (isspace(*token))
      |                            ^~~~~~

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>