aes: Avoid defining an already defined macro
printf() is already defined as a macro when the compiler in use does not
support __va_arg_pack, which is the case for e.g. clang:

../../../src/swtpm/swtpm_aes.c:55:9: error: 'printf' macro redefined
[-Werror,-Wmacro-redefined]
        ^
/usr/include/bits/stdio2.h:115:11: note: previous definition is here
          ^
1 error generated.

Signed-off-by: Timm Bäder <tbaeder@redhat.com>